<?php

namespace Container6VdH9K8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VqkG81xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VqkG81x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VqkG81x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'indicatorRepository' => ['privates', 'App\\Repository\\IndicatorRepository', 'getIndicatorRepositoryService', true],
        ], [
            'doctrine' => '?',
            'indicatorRepository' => 'App\\Repository\\IndicatorRepository',
        ]);
    }
}
