<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxKI49u\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxKI49u/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGxKI49u.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGxKI49u\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerGxKI49u\App_KernelTestDebugContainer([
    'container.build_hash' => 'GxKI49u',
    'container.build_id' => 'b94e7d30',
    'container.build_time' => 1690621466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxKI49u');
