<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTLfGypR\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTLfGypR/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTLfGypR.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTLfGypR\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerTLfGypR\App_KernelTestDebugContainer([
    'container.build_hash' => 'TLfGypR',
    'container.build_id' => 'c55351c9',
    'container.build_time' => 1685699672,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTLfGypR');
