<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4ajxHy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4ajxHy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4ajxHy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4ajxHy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX4ajxHy\App_KernelDevDebugContainer([
    'container.build_hash' => 'X4ajxHy',
    'container.build_id' => '5991fc7d',
    'container.build_time' => 1690023603,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4ajxHy');
